server {
    listen 8443 ssl;
    server_name api.payshield.local localhost;

    ssl_certificate     /tmpfs/certs/server.crt;
    ssl_certificate_key /tmpfs/certs/server.key;
    ssl_client_certificate /kms/ca.crt;
    ssl_verify_client      on;
    ssl_verify_depth       2;

    location / {
        proxy_pass https://kong:8443;
        proxy_set_header Host                    $host;
        proxy_set_header X-Real-IP               $remote_addr;
        proxy_set_header X-Forwarded-For         $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto       $scheme;
        proxy_set_header X-Forwarded-Client-Cert $ssl_client_escaped_cert;
        proxy_ssl_certificate         /tmpfs/certs/server.crt;
        proxy_ssl_certificate_key     /tmpfs/certs/server.key;
        proxy_ssl_trusted_certificate /kms/ca.crt;
        proxy_ssl_verify      on;
        proxy_ssl_server_name on;
        proxy_ssl_name        payshield.local;
    }
}