server {
    listen 8443 ssl;
    server_name api.payshield.local localhost;

    # 1. Cấu hình Certificate cho WAF (để trình duyệt tin tưởng)
    ssl_certificate /etc/nginx/certs/waf.crt;
    ssl_certificate_key /etc/nginx/certs/waf.key;

    # 2. KÍCH HOẠT mTLS: Đòi chứng chỉ từ Postman
    ssl_client_certificate /etc/nginx/certs/ca.crt;
    ssl_verify_client on; 
    ssl_verify_depth 2;

    # 3. Cấu hình Proxy sang Kong
    proxy_ssl_verify off;
    proxy_ssl_server_name on;
    proxy_ssl_name "payshield_kong";
    
    # Dùng chứng chỉ của WAF để bắt tay mTLS với Kong
    proxy_ssl_certificate /etc/nginx/certs/waf.crt;
    proxy_ssl_certificate_key /etc/nginx/certs/waf.key;

    location / {
        proxy_pass https://payshield_kong:8443; # Đổi từ payshield_kong sang kong cho chuẩn Docker DNS
        proxy_set_header X-Forwarded-Client-Cert $ssl_client_escaped_cert;
        
        # Các header bổ trợ
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}