input {
  beats { 
    port => 5044
    ssl => true 
    ssl_certificate => "/usr/share/logstash/config/certs/db_client.crt"
    ssl_key => "/usr/share/logstash/config/keys/db_client.key"
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca.crt"]
    ssl_verify_mode => "none"
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"] 
    ssl_certificate_verification => false 
    user => "elastic"
    password => "${ELK_PASSWORD}"
    index => "siem-logs-%{+YYYY.MM.dd}"
  }
}