input {
  beats { 
    port => 5044
    ssl => true 
    ssl_certificate => "/usr/share/logstash/config/certs/elk.crt"
    ssl_key => "/usr/share/logstash/config/certs/elk.key"
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca.crt"]
    ssl_verify_mode => "force_peer" 
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"] 
    user => "elastic"
    password => "${ELK_PASSWORD}"
    index => "siem-logs-%{+YYYY.MM.dd}"
    ssl_enabled => true
    ssl_verification_mode => "none"
    cacert => "/usr/share/logstash/config/certs/ca.crt"
    ssl_key => "/usr/share/logstash/config/certs/elk.key"
    ssl_certificate => "/usr/share/logstash/config/certs/elk.crt"
  }
}