input {
  beats { 
    port => 5044
    ssl => true 
    ssl_certificate => "/tmpfs/certs/server.crt"
    ssl_key => "/tmpfs/certs/server.key"
    ssl_certificate_authorities => ["/etc/ssl/certs/ca.crt"]
    ssl_verify_mode => "force_peer" 
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"] 
    user => "elastic"
    password => "${ELK_PASSWORD}"
    index => "siem-logs-%{+YYYY.MM.dd}"
    ssl => true
    ssl_certificate_verification => false
    cacert => "/etc/ssl/certs/ca.crt"
  }
}