server {
    listen 8443 ssl;
    server_name localhost;

    ssl_certificate           /etc/nginx/certs/laravel.crt;
    ssl_certificate_key       /etc/nginx/certs/laravel.key;
    ssl_client_certificate    /etc/nginx/certs/ca.crt;
    ssl_verify_client         on;

    location / {
        proxy_pass http://app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}