openapi: 3.0.3
info:
  title: Payshield API
  version: 1.0.0
servers:
  - url: https://localhost:8888/api
paths:
  /dashboard/manager-data:
    get:
      summary: GET Dashboard Manager
      responses:
        "200":
          description: OK
          
  /employees:
    get:
      summary: GET Roster
      parameters:
        - name: pentest
          in: query
          description: Tham số chứa payload để test WAF
          schema:
            type: string
          examples:
            sqli:
              summary: SQL Injection
              value: "1' UNION SELECT username, password FROM users--"
            xss:
              summary: Cross-Site Scripting
              value: "<script>alert('Hacked!')</script>"
            lfi:
              summary: Local File Inclusion
              value: "C:\\Windows\\System32\\cmd.exe"
            cmd_inject:
              summary: Command Injection
              value: "127.0.0.1;cat /etc/passwd"
            log_inject:
              summary: Log Injection
              value: "admin%0d%0a[INFO] User logged in successfully"
      responses:
        "200":
          description: OK
        "403":
          description: Block by WAF
            
  /employees/{employeeId}:
    parameters:
      - name: employeeId
        in: path
        required: true
        schema:
          type: string
          example: "NV000"
    get:
      summary: GET Employees
      responses:
        "200":
          description: OK
    put:
      summary: PUT Employees
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                CHUCVU:
                  type: string
                  example: "Example"
      responses:
        "200":
          description: OK
    delete:
      summary: DELETE Employees
      responses:
        "200":
          description: OK
          
  /payrolls:
    get:
      summary: GET Payroll
      parameters:
        - name: month
          in: query
          schema:
            type: integer
            example: 3
        - name: year
          in: query
          schema:
            type: integer
            example: 2026
      responses:
        "200":
          description: OK
          
  /dashboard/employee-data:
    get:
      summary: GET Dashboard Employee
      responses:
        "200":
          description: OK
          
  /profile:
    get:
      summary: GET Profile
      responses:
        "200":
          description: OK
          
  /salary:
    get:
      summary: GET Salary
      responses:
        "200":
          description: OK

  /vnpay/create:
    post:
      summary: POST VNPay
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  example: 500000
      responses:
        "200":
          description: OK